"""Provider-neutral interface exposed by the web_ui anti-corruption layer."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .contracts import (
    ArtifactObservation,
    ActivitySnapshot,
    AuthenticationState,
    CompatibilityReport,
    ComposerSnapshot,
    RequestScope,
    TurnRef,
    UIResponse,
    UISnapshot,
)


@runtime_checkable
class WebUIProviderAdapter(Protocol):
    """The only DOM-facing interface runtime/workflow code may consume."""

    provider_name: str
    page: Any

    def probe_compatibility(self, *, force: bool = False) -> CompatibilityReport: ...
    def require_compatible(self) -> CompatibilityReport: ...
    def visible_composer(self) -> Any: ...
    def send_control(self) -> Any: ...
    def composer_snapshot(self) -> ComposerSnapshot: ...
    def validate_composer(self, prompt: str): ...
    def stop_controls(self) -> tuple: ...
    def generation_active(self) -> bool: ...
    def turns(self, role: str) -> tuple[TurnRef, ...]: ...
    def observation_turns(self, role: str) -> tuple[TurnRef, ...]: ...
    def element_fingerprint(self, element: Any) -> str: ...
    def rendered_turn_text(self, turn: TurnRef | object | None) -> str: ...
    def turn_attachment_signatures(self, turn: TurnRef | object | None) -> tuple[str, ...]: ...
    def disconnect_signature_visible(self) -> bool: ...
    def page_reachable(self) -> bool: ...
    def authentication_state(self) -> AuthenticationState: ...
    def artifact_observations(self, root: Any | None = None) -> tuple[ArtifactObservation, ...]: ...
    def snapshot(self) -> UISnapshot: ...
    def capture_request(self, prompt: str, *, conversation_id: str = "") -> RequestScope: ...
    def confirm_user_turn(self, scope: RequestScope) -> TurnRef | None: ...
    def reconcile_user_turn(
        self, scope: RequestScope
    ) -> tuple[TurnRef | None, dict[str, Any]]: ...
    def rebind_user_turn(self, scope: RequestScope) -> TurnRef | None: ...
    def conversation_unit_id(self, turn: TurnRef) -> str: ...
    def durable_turn_id(self, turn: TurnRef) -> str: ...
    def analysis_complete_visible(self, assistant: TurnRef | object | None = None) -> bool: ...
    def latest_owned_assistant(self, scope: RequestScope) -> TurnRef | None: ...
    def assistant_wait_fallbacks(
        self, markers: tuple[str, ...], *, limit: int = 3
    ) -> dict: ...
    def latest_conversation_turn(self) -> TurnRef | None: ...
    def extract_final_text(self, assistant: TurnRef | object | None) -> str: ...
    def activity(self, assistant: TurnRef | object | None = None) -> ActivitySnapshot: ...
    def media_state(self, assistant: TurnRef | object | None = None) -> dict: ...
    def install_activity_observer(self) -> None: ...
    def install_input_bridge(self, *, reset_legacy: bool = False) -> None: ...
    def input_bridge_installed(self) -> bool: ...
    def pop_input_bridge(self) -> dict | None: ...
    def set_automation_submit(self, active: bool) -> None: ...
    def attachment_file_inputs(self) -> tuple: ...
    def attachment_button(self) -> Any: ...
    def attachment_menu_items(self) -> tuple: ...
    def attachment_dom_state(self, expected_names: list[str]) -> dict: ...
    def composer_attachment_count(self) -> int: ...
    def clear_one_attachment(self) -> bool: ...
    def dismiss_rate_limit_dialog(self) -> bool: ...
    def conversation_display_name(self) -> str: ...
    def conversation_link(self, conversation_id: str) -> Any: ...
    def dismiss_blocking_dialog(self) -> dict: ...
    def activity_observer_state(self) -> dict: ...


__all__ = ["WebUIProviderAdapter"]
